name: MythicPrefixes
version: '${project.version}'
main: cn.superiormc.mythicprefixes.MythicPrefixes
api-version: '1.13'
folia-supported: true
softdepend:
  - PlaceholderAPI
  - MythicLib
  - MythicMobs
  - floodgate
commands:
  mythicprefixes:
    aliases:
      - "prefix"
      - "prefixes"
    usage: "/mythicprefixes"
    description: "MythicPrefixes Main Command."
permissions:
  mythicprefixes.opengui:
    default: true
  mythicprefixes.addprefix:
    default: op
  mythicprefixes.reload:
    default: op
  mythicprefixes.removeprefix:
    default: op
  mythicprefixes.setprefix:
    default: op
  mythicprefixes.viewusingprefix:
    default: true