name: MythicPrefixes
version: '${project.version}'
main: cn.superiormc.mythicprefixes.MythicPrefixes
api-version: '1.13'
softdepend:
  - PlaceholderAPI
  - MythicLib
libraries:
  - cc.carm.lib:easysql-hikaricp:0.4.7
commands:
  mythicprefixes:
    aliases:
      - "prefix"
      - "prefixes"
    usage: "/mythicprefixes"
    description: "MythicPrefixes Main Command."