# Remove whole display item section to make it hide in GUI
display-item:
  unlocked:
    material: DRAGON_EGG
    name: '{display-value}'
    lore:
      - '&7Preview: %mythicprefixes_prefix_default_chat% %player_name%'
      - '&dOp will always can use the tag, give'
      - '&dyourself &4-mythicprefixes.bypass.*'
      - '&dpermission to avoid that.'
      - '&eClick to use!'
  using:
    material: DRAGON_EGG
    name: '{display-value}'
    lore:
      - '&7Preview: %mythicprefixes_prefix_default_chat% %player_name%'
      - '&cYou are now using this prefix!'
      - '&eClick to cancel use this prefix!'
  locked:
    material: DRAGON_EGG
    name: '&cLocked'
    lore:
      - '&7Preview: %mythicprefixes_prefix_default_chat% %player_name%'
      - '&cKill a dragon to unlock!'
  max-reached:
    material: DRAGON_EGG
    name: '{display-value}'
    lore:
      - '&7Preview: %mythicprefixes_prefix_default_chat% %player_name%'
      - '&cYou have reached max use of prefix!'
display-value: '&8Dragon Killer'
weight: 15
effects:
  libreforge: false
  MythicLib: false
MythicLib-effects:
  1:
    stat: MAX_HEALTH
    value: 1
equip-actions:
  - 'message: Start equip the tag!'
unequip-actions:
  - 'message: Not equip the tag!'
circle-actions:
  - 'console_command: say Wow!'
conditions:
  - 'permission: killed.dragon'
